name: appdemo
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localization:
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/fast-food.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/icon/
